name: Canary Build

on:
  # 手动触发
  workflow_dispatch:
  # 每隔3小时触发构建，以便快速发版，验证错误
  schedule:
    - cron: '0 */3 * * *'


permissions: write-all

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: set beijing timezone
        uses: szenius/set-timezone@v1.2 # 设置虚拟环境的时区，可更改时区
        with:
          timezoneLinux: "Asia/Shanghai"
      - name: 下载代码
        uses: actions/checkout@v2
        with:
          repository: daomengRen/AutoAccounting
          fetch-depth: 0
      - name: 设置Java编译环境
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: 编译安卓
        run: |
          pip install requests md2tgmd  && python .github/workflows/main.py
        env:
          # 工作目录  os.getenv("GITHUB_WORKSPACE") or os.getcwd()
          WORKSPACE: ${{ secrets.WORKSPACE }}  
          # cloud.ankio.net 发送到 网盘 使用   不需要
          ALIST_TOKEN: ${{ secrets.ALIST_TOKEN }}
          #  forum.ez-book.org 发送到 论坛 使用  不需要
          FORUMS_API_KEY: ${{ secrets.FORUMS_API_KEY }}
          BUILD_TOOLS_VERSION: 34.0.0
          # sign_apk 打包apk的时候使用
          SIGN_ALIAS: ${{ secrets.SIGN_ALIAS }}
          SIGN_PASSWORD: ${{ secrets.SIGN_PASSWORD }}
          # 结束
          # GitHub token 发布到 Github 使用  需要
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # TELEGRAM  发送到 TELEGRAM 使用  不需要
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHANNEL: Canary





